version: "1.0"
instances:

  nginx:
    build:
      context: ./nginx
      recipe: Singularity.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par
    volumes_from:
      - app
    ports:
      - "80"

  db:
    image: docker://postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: ./app
    volumes:
      - .:/code
      - ./static:/var/www/static
      - ./images:/var/www/images
    ports:
      - "5000:80"
    depends_on:
      - nginx
