version: "1.0"
instances:

  nginx:
    build:
      context: ./nginx
      recipe: Singularity.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par
    ports:
      - 80:80
    volumes_from:
      - app

  db:
    image: docker://postgres:9.4
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
  app:
    build:
      context: ./app
    volumes:
      - ./app:/code
      - ./static:/var/www/static
      - ./images:/var/www/images
    ports:
      - 5000:5000
    depends_on:
      - nginx
      - db
