version: "1.0"
services:

  nginx:
    build:
      context: ./nginx
      singularity: Singularity.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
    volumes_from:
      - uwsgi
    ports:
      - "80"

  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data

  uwsgi:
    build:
      context: ./app
    volumes:
      - .:/code
      - ./static:/var/www/static
      - ./images:/var/www/images
    ports:
      - "5000:80"
    depends_on:
      - nginx
